- name: Create /opt/python directory
  raw: mkdir -p /opt/python 

- name: Check if bootstrap is needed
  raw: stat /opt/python/.bootstrapped
  register: need_bootstrap
  ignore_errors: True
  changed_when: "need_bootstrap.rc != 0"

- name: Run bootstrap.sh
  script: bootstrap.sh
  when: need_bootstrap is failed

- name: Check if we need to install pip
  shell: "{{ansible_python_interpreter}} -m pip --version"
  register: need_pip
  ignore_errors: True
  changed_when: false
  when: need_bootstrap is failed

- name: Copy get-pip.py
  copy: src=get-pip.py dest=/opt/python/get-pip.py
  when: need_pip is failed

- name: Install pip
  shell: "{{ansible_python_interpreter}} /opt/python/get-pip.py"
  when: need_pip is failed

- name: Remove get-pip.py
  file: path=/opt/python/get-pip.py state=absent
  when: need_pip is failed

- name: Install pip launcher
  copy: src=runner dest=/opt/python/bin/pip mode=0755
  when: need_pip is failed

- name: Check if we need to install docker-py
  shell: "{{ansible_python_interpreter}} -c 'import docker'"
  register: need_docker_module
  ignore_errors: True
  changed_when: false

- name: Install docker-py
  shell: "{{ansible_python_interpreter}} -m pip install docker"
  when: need_docker_module is failed

